apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    app: nginx-lb
    demo: service
spec:
  containers:
  - name: nginx-lb
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:  
  name: nginx-nodeport
spec:
  type: LoadBalancer
  selector:
    app: nginx-lb
    demo: service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80