apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: hello-pod 
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux 
    image: almalinux:8
    command: ["sleep", '300'] 