apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: Devops
    trainner: rajesh
  annotations:
    com.roboshop.author: "120 hours"
spec:
  containers:
  - name: hello-pod 
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux 
    image: almalinux:8
    command: ["sleep", '300'] 