apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hello-pod 
    image: nginx
    ports:
    - containerPort: 80
    resources:  # Corrected from 'resource' to 'resources'
      requests:  # Corrected from 'request' to 'requests'
        cpu: "100m"
        memory: "68Mi"  # Corrected from '68mi' to '68Mi'
      limits:
        cpu: "200m"
        memory: "128Mi"  # Corrected from '128mi' to '128Mi'
