apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hello-pod 
    image: nginx
    ports:
    - containerPort: 80
    resource:
      request:
        cpu: "100m"
        memory: "68mi"
      limits:
        cpu: "200m"
        memory: "128mi"