apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop
spec:
  containers:
  - name: hello-pod 
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: config-pod
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: config-pod
          key: course