apiVersion: v1
kind: Pod
metadata:
  name: devops-config
spec:
  containers:
  - name: hello-pod 
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
      secretKeyRef:
        name: devops-secrate
          
 