apiVersion: v1
kind: Pod
metadata:
  name: devops-secret-pod  
spec:
  containers:
  - name: hello-pod 
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef: 
        name: devops-secret  
